// Tests for the Post Controller

### Posts endpoint
@domain = http://localhost:3000/
@endpoint = posts/
@url = {{domain}}{{endpoint}}


### Create Post
# @name createPost
@title = "Title of the new, new, new post"
@content = "Content of another the new post. Bla, bla, blaaaaa."
@categoryName = "Post, v6"
@userId = 2
POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "title": {{title}},
    "content": {{content}},
    "categoryName": {{categoryName}},
    "userId": {{userId}}
}


### Search the Posts of a User by Category
@searchCategoryName = "Silly post, v2"
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}},
    "categoryName": {{searchCategoryName}}
}


### Search the Posts of a User by Category, but Category not exists
@nonExistentCategory = "A non-existent category"
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}},
    "categoryName": {{nonExistentCategory}}
}


### Search the Posts of a User, Category not specified, so any Category
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}}
}


### Search the Posts of a User, User does not exist
@nonExistentUserId = -10
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{nonExistentUserId}}
}


### Search Posts by Category; no User specified, so any User
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "categoryName": {{searchCategoryName}}
}


### Search Posts by Category, but non-existent Category
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "categoryName": {{nonExistentCategory}}
}
