// Tests for the Post Search Controller

### Posts endpoint
@domain = http://localhost:3000/
@endpoint = posts/
@url = {{domain}}{{endpoint}}


### Search the Posts of a User by Category
### Return Status 200
@userId = 2
@searchCategoryName = "Silly post, v2"
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}},
    "categoryName": {{searchCategoryName}}
}


### Search the Posts of a User by Category, but Category not exists
### Return Status 200
@nonExistentCategory = "A non-existent category"
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}},
    "categoryName": {{nonExistentCategory}}
}


### Search the Posts of a User, Category not specified, so any Category
### Return Status 200
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}}
}


### Search the Posts of a User, User does not exist
### Return Status 404
@nonExistentUserId = -10
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{nonExistentUserId}}
}


### Search Posts by Category; no User specified, so any User
### Return Status 200
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "categoryName": {{searchCategoryName}}
}


### Search Posts by Category, but non-existent Category
### Return Status 404
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "categoryName": {{nonExistentCategory}}
}
