// Tests for the User Controller

### Users endpoint
@domain = http://localhost:3000/
@endpoint = users/
@url = {{domain}}{{endpoint}}


### Create User
### Return Status 201
# @name createUser
POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "nickname": "jose jose"
}


### Read last created User
### Return Status 200
@userId = {{createUser.response.body.$.user.id}}
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{userId}}
}


### Search User by id
### Return Status 200
@id = 3
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{id}}
}


### Search User by nickname
### Return Status 200
@nickname = "jose"
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "nickname": {{nickname}}
}


### Search non-existent User
### Return Status 404
@nicknameNotInDB = "miguel"
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "nickname": {{nicknameNotInDB}}
}


### Search User, wrong parameters
### Return Status 400
GET {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": {{nickname}}
}

