// Tests for the Authentication Controller

### Authentication endpoints
@domain = http://localhost:3000/
@loginEndpoint = login/
@logoutEndpoint = logout/
@loginUrl = {{domain}}{{loginEndpoint}}
@logoutUrl = {{domain}}{{logoutEndpoint}}


### Request Token for an existing User, right password
### Return Status 200
# @name loginUser
@userName = "johnson"
@userPassword = "benny999"
POST {{loginUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": {{userName}},
    "password": {{userPassword}}
}


### Variables required for subsequent requests
@id = {{loginUser.response.headers.id}}
@token = {{loginUser.response.headers.token}}


### Try to logout an User that is logged in, wrong session
### Return Status 200, but don't log out (see database)
POST {{logoutUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json
id: {{id}}
token: NOT_VALID_TOKEN


### Try to logout an existing User, right session, wrong format for id
### Return Status 400, don't logout
POST {{logoutUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json
id: NOT_VALID_ID
token: {{token}}


### Try to logout an existing User, missing token
### Return Status 400, don't logout
POST {{logoutUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json
id: {{id}}


### Try to logout an existing User, missing user id
### Return Status 400, don't logout
POST {{logoutUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json
token: {{token}}


### Logout an existing User, right session
### Return Status 200; logout if user is logged in
POST {{logoutUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json
id: {{id}}
token: {{token}}


### Request Token for a non-existing User
### Return Status 400
@userNameNonExistent = "juancho"
POST {{loginUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": {{userNameNonExistent}},
    "password": {{userPassword}}
}


### Request Token for an existing User, but wrong password
### Return Status 400
@passwordWrong = "johnsonsPass"
POST {{loginUrl}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": {{userName}},
    "password": {{passwordWrong}}
}

