// Tests for the User Controller

### Users endpoint
@domain = http://localhost:3000/
@endpoint = users/
@url = {{domain}}{{endpoint}}


### Create User, default values for Role and email
### Return Status 201
# @name createUser
POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "jameson",
    "dni": "25777777",
    "password": "jameson999",
    "role": "zeeper",
    "email": "jameson@gmail.com"
}


### Read last created User
### Return Status 200
@userId = {{createUser.response.body.$.user.id}}
GET {{url}}{{userId}} HTTP/1.1
Accept: application/json


### Update last created User
### Return Status 200
@userId = {{createUser.response.body.$.user.id}}
PATCH {{url}}{{userId}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "id": {{userId}},
    "dni": "25000111",
    "email": "newjohnsonsmail@gmail.com"
}


### try to Create User, fail with errors
### Return Status 400
POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "judas",
    "dni": "25666666",
    "password": "j"
}


### Read an existing User
### Return Status 200
@id = 38
GET {{url}}{{id}} HTTP/1.1
Accept: application/json


### Read a non-existent User
### Return Status 200
@userIdNonExistent = -10
GET {{url}}{{userIdNonExistent}} HTTP/1.1
Accept: application/json


### Read a User, wrong parameters
### Return Status 200
@userIdWrongValue = juan
GET {{url}}{{userIdWrongValue}} HTTP/1.1
Accept: application/json

